#Include monkey_meadow.ahk
#Include in_the_loop.ahk
#Include middle_of_the_road.ahk
#Include tinkerton.ahk
#Include tree_stump.ahk
#Include town_center.ahk
#Include one_two_tree.ahk
#Include scrapyard.ahk
#Include the_cabin.ahk
#Include resort.ahk
#Include skates.ahk
#Include lotus_island.ahk
#Include candy_falls.ahk
#Include winter_park.ahk
#Include carved.ahk
#Include park_path.ahk
#Include alpine_run.ahk
#Include frozen_over.ahk
#Include cubism.ahk
#Include four_circles.ahk
#Include hedge.ahk
#Include end_of_the_road.ahk
#Include logs\main.ahk
